name: CI

on:
    push: 
      branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Executar uma linha de comando
        run: echo Meu primeiro comando com o gitActions


        
